# Generated by Django 5.1.4 on 2024-12-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artistas', '0001_initial'),
        ('generos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Título del Disco')),
                ('fecha_lanzamiento', models.DateField(verbose_name='Fecha de Lanzamiento')),
                ('artistas', models.ManyToManyField(related_name='discos', to='artistas.artista', verbose_name='Artistas')),
                ('generos', models.ManyToManyField(related_name='discos', to='generos.generomusical', verbose_name='Géneros Musicales')),
            ],
        ),
    ]
