# Generated by Django 5.1.4 on 2024-12-14 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Red Social')),
                ('enlace', models.URLField(verbose_name='Enlace a la Red Social')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociales', to='artistas.artista')),
            ],
        ),
    ]
