# Generated by Django 5.1.4 on 2024-12-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Real')),
                ('nombre_artistico', models.CharField(max_length=100, unique=True, verbose_name='Nombre Artístico')),
                ('biografia', models.TextField(verbose_name='Biografía')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
            ],
        ),
    ]
