<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-12-17 18:47
=======
# Generated by Django 5.1.3 on 2024-12-12 01:50
>>>>>>> 34475f7fd07ba1dcba06a7ba3e9370378f3e2418

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('genero_musical', '0001_initial'),
>>>>>>> 34475f7fd07ba1dcba06a7ba3e9370378f3e2418
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Real')),
                ('nombre_artistico', models.CharField(max_length=100, unique=True, verbose_name='Nombre Artístico')),
                ('biografia', models.TextField(verbose_name='Biografía')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
=======
            name='Artistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_artistico', models.CharField(max_length=100)),
                ('biografia', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
                ('foto', models.ImageField(upload_to='artistas')),
                ('redes_sociales', models.JSONField(default=dict)),
                ('generos_musicales', models.ManyToManyField(to='genero_musical.generosmusicales')),
>>>>>>> 34475f7fd07ba1dcba06a7ba3e9370378f3e2418
            ],
        ),
    ]
