# Generated by Django 5.1.4 on 2024-12-14 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título de la Canción')),
                ('duracion', models.DurationField(verbose_name='Duración de la Canción')),
                ('fecha_lanzamiento', models.DateField(verbose_name='Fecha de Lanzamiento')),
                ('disco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='discos.disco', verbose_name='Disco')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('titulo', 'disco'), name='unique_titulo_por_disco')],
            },
        ),
    ]
