<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-12-17 18:47
=======
# Generated by Django 5.1.3 on 2024-12-12 01:50
>>>>>>> 34475f7fd07ba1dcba06a7ba3e9370378f3e2418

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('discos', '0001_initial'),
        ('generos', '0001_initial'),
=======
        ('artistas', '0001_initial'),
        ('discos', '0001_initial'),
>>>>>>> 34475f7fd07ba1dcba06a7ba3e9370378f3e2418
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título de la Canción')),
                ('duracion', models.DurationField(verbose_name='Duración de la Canción')),
                ('fecha_lanzamiento', models.DateField(verbose_name='Fecha de Lanzamiento')),
                ('disco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='discos.disco', verbose_name='Disco')),
                ('genero_musical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generos.generomusical')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('titulo', 'disco'), name='unique_titulo_por_disco')],
            },
=======
            name='Canciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('duracion', models.DurationField()),
                ('fecha_lanzamiento', models.DateField()),
                ('letra', models.TextField()),
                ('audio', models.FileField(upload_to='audios')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='discos.discos')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistas.artistas')),
            ],
>>>>>>> 34475f7fd07ba1dcba06a7ba3e9370378f3e2418
        ),
    ]
