# Generated by Django 5.1.3 on 2024-12-12 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canciones',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='canciones',
            name='letra',
        ),
    ]
