# Generated by Django 5.1.4 on 2024-12-20 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cancion',
            name='unique_titulo_por_disco',
        ),
    ]
