# Generated by Django 5.1.3 on 2024-12-12 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canciones', '0002_remove_canciones_audio_remove_canciones_letra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canciones',
            name='artista',
        ),
    ]
