# Generated by Django 5.1.4 on 2024-12-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canciones', '0002_remove_cancion_unique_titulo_por_disco'),
        ('discos', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cancion',
            constraint=models.UniqueConstraint(fields=('titulo', 'disco'), name='unique_titulo_por_disco'),
        ),
    ]
