<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-12-17 18:47

=======
# Generated by Django 5.1.3 on 2024-12-12 01:50

import django.db.models.deletion
>>>>>>> 34475f7fd07ba1dcba06a7ba3e9370378f3e2418
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artistas', '0001_initial'),
<<<<<<< HEAD
=======
        ('genero_musical', '0001_initial'),
>>>>>>> 34475f7fd07ba1dcba06a7ba3e9370378f3e2418
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Título del Disco')),
                ('fecha_lanzamiento', models.DateField(verbose_name='Fecha de Lanzamiento')),
                ('artistas', models.ManyToManyField(related_name='discos', to='artistas.artista', verbose_name='Artistas')),
=======
            name='Discos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_lanzamiento', models.DateField()),
                ('portada', models.ImageField(upload_to='discos')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistas.artistas')),
                ('generos_musicales', models.ManyToManyField(to='genero_musical.generosmusicales')),
>>>>>>> 34475f7fd07ba1dcba06a7ba3e9370378f3e2418
            ],
        ),
    ]
