# Generated by Django 5.1.3 on 2024-12-12 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discos', '0002_remove_discos_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discos',
            name='generos_musicales',
        ),
    ]
